WHAT IS NUMPY:

Numpy is the fundamental package for scientific computing in python.It is a python library that provides a multidimensional array object,various derived object and an assortment of routines for fast operations on arrays including mathematical,logical,shape manipulation,sorting,selecting,I/O,discrete Fourier transforms,basic linear algebra,basic statistical operations,random simulation & much more..
    At the core of the Numpy package,is the ndarray object.This encapsulates n-dimensional arrays of homogeneous data types.


NUMPY ARRAYS VS PYTHON SEQUENCES:

> Numpy arrays have a fixed size at creation, unlike python lists.Changing the size of an ndarray will create a new array and delete the original.
> The elements in a Numpy array are all required to be of the same data type, and thus willbe the same size in memory.
> Numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data.Typically such operations are executed more efficiently and with less code than is possible using python's built in sequences.
> A growing plethora of scientific and mathematical python based packages are using numpy arrays; though these typically support python sequence input they convert such input to numpy arrays prior to processing and they often output numpy arrays.


In [2]:
# CREATING NUMPY ARRAY:
# 1D

import numpy as np
a= np.array([1,2,3,4,5,6,7,8,9])
print(type(a))

<class 'numpy.ndarray'>


In [4]:
# 2D

b= np.array([[1,2],[3646575,46464]])
print(b)

[[      1       2]
 [3646575   46464]]


In [5]:
# 3D

c = np.array([[1,2],[3,4],[5,6]])
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
# data type

np.array([1,2,3],dtype = float)

np.array([1,3,4,4],dtype = bool)
np.array([1,3,4,4],dtype = complex)

array([1.+0.j, 3.+0.j, 4.+0.j, 4.+0.j])

In [11]:
# np.arange
np.arange(1,11,2)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# with reshape
import numpy as np
np.arange(1,11).reshape(2,5)
 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [5]:
# np.ones and np.zeros
np.ones((3,4))
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
# np.random
np.random.random((2,3))

array([[0.30938055, 0.7533939 , 0.54128892],
       [0.57285026, 0.46321252, 0.56901037]])

In [7]:
# np.linearspace(linearly generate values from equal distance)
np.linspace(-10,10,10)  # upperrange,lowerrange,no of items

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [9]:
np.linspace(-10,10,10,dtype= int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [8]:
# np.identity
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
# ARRAY ATTRIBUTES
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [19]:
# ndim(no of dimensions)
a2.ndim

2

In [22]:
# shape
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [24]:
# size
a3.size
a2.size

12

In [26]:
# itemsize
a1.itemsize
a2.itemsize

8

In [28]:
# datatype
print(a1.dtype)
print(a2.dtype)


int32
float64


In [36]:
# CHANGING DATATYPES
a2.dtype
a2.astype(np.float32)


dtype('float64')

In [38]:
# ARRAY OPERATIONS:
a1= np.arange(12).reshape(3,4)
a2= np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
# scalar operations:: for all arithmetic operations
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [43]:
# relational
a1>5
a2>5
a2==13
a2!=23

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [44]:
# vector operations: for all arithmetic operations
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [47]:
# ARRAY FUCTIONS:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[88., 34., 22.],
       [85., 87., 61.],
       [15.,  9., 37.]])

In [49]:
# max,min,sum,product
np.max(a1)
np.min(a1)
np.

9.0